Numpy

In [22]:
lst = [10, 20, 30]
# avaerage(lst)

In [23]:
import numpy as np

np.mean(lst)

np.float64(20.0)

In [24]:
np.linspace(1, 8, 20)

array([1.        , 1.36842105, 1.73684211, 2.10526316, 2.47368421,
       2.84210526, 3.21052632, 3.57894737, 3.94736842, 4.31578947,
       4.68421053, 5.05263158, 5.42105263, 5.78947368, 6.15789474,
       6.52631579, 6.89473684, 7.26315789, 7.63157895, 8.        ])

In [25]:
number = [1, 2, 3, 4, 5, 6]
numbernp = np.array(number)
print(type(number))
type(numbernp)

print(number)
print(numbernp)

<class 'list'>
[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]

In [26]:
numbernp.max()

np.int64(6)

In [27]:
print(np.min(numbernp))

1

In [30]:
n = [4,6,7,3,4,5,7,9,1]
print(n)
n.sort()
print(n)

[4, 6, 7, 3, 4, 5, 7, 9, 1]
[1, 3, 4, 4, 5, 6, 7, 7, 9]

In [32]:
n = [4,6,7,3,4,5,7,9,1]
print(type(n))
n = np.sort(n)
print(type(n))

<class 'list'>
<class 'numpy.ndarray'>

Pandas

In [34]:
import pandas as pd

# create some random data

var1 = np.random.randn(100)*5 + 20

var1

array([16.93063056, 28.34350674, 26.65418961, 28.35075811, 31.11918531,
       29.28956692, 23.48704615, 24.62464167, 10.37558036, 14.28574362,
       15.86150826, 17.33128411, 16.79390166, 18.10977033, 18.01231777,
        7.31877805, 16.45809487, 27.86046982, 14.25922149, 24.32844415,
       22.91096076, 13.9942919 ,  7.45593873, 21.5276071 , 28.83678261,
       24.74428391, 18.04002707, 19.83866409, 21.70764435, 17.27487522,
       21.95571839, 11.032259  , 24.93146354, 21.77263598, 26.18473388,
       18.63495099, 22.42161222, 14.26099674, 24.41735579, 21.57333215,
       31.01828456, 21.8529263 , 22.05592991, 26.36323864, 23.56907911,
       16.1450903 , 15.17287307, 26.86877745, 12.0033201 , 14.46159831,
       23.34953551, 26.38572082, 14.35045158, 14.99853261, 18.55681568,
       21.5700726 , 24.53798702, 18.19329026, 23.38126556, 26.88853869,
        8.91615569, 15.85247261, 16.70806556, 13.51294069, 16.92632755,
       34.10131264, 13.62710425, 17.76645775, 17.17796055, 22.29128572,
       21.343135  , 19.80634761, 17.86095847, 20.44185261, 26.19043443,
       16.54733686, 19.16547818, 15.43283723, 16.93480176, 15.85688464,
       21.51410816, 20.86349597, 22.84959083, 21.14740648, 23.58771855,
       26.6801581 , 21.97260886, 16.37556944, 30.70772375, 21.92723128,
       22.42882342, 21.97026198, 21.04019975, 12.72274959, 24.73311876,
       22.56394179, 14.21868275, 13.81741483, 24.64268798, 18.04549497])

In [36]:
var2 =  np.random.randn(100)>0

var2

array([ True,  True, False,  True,  True, False, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
       False,  True, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True,  True, False, False,  True,  True,  True, False,  True,
       False, False, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True, False,  True,
       False])

In [46]:
import pandas as pd

# create some random data

var1 = np.random.randn(100)*5 + 20
var2 =  np.random.randn(100)>0

labels = ['Temp. (C)', 'Ice cream  eaten']

# create a dictionary

D = {labels[0]: var1, labels[1]: var2 }


# import the dictionary into a pandas dataframe


df = pd.DataFrame(data=D)
df

    Temp. (C)  Ice cream  eaten
0   13.052510              True
1   22.879097             False
2   23.671052              True
3   26.942444              True
4   19.741311             False
..        ...               ...
95  19.617658              True
96  12.278859              True
97  23.435274             False
98  12.409888             False
99  21.463603             False

[100 rows x 2 columns]

In [49]:
df.head(12)

    Temp. (C)  Ice cream  eaten
0   13.052510              True
1   22.879097             False
2   23.671052              True
3   26.942444              True
4   19.741311             False
5   17.318494             False
6   14.606521              True
7   21.255918             False
8   18.784077              True
9   22.811682             False
10  20.629408             False
11  17.994160              True

In [52]:
df.count()

Temp. (C)           100
Ice cream  eaten    100
dtype: int64

In [54]:
df.mean()

Temp. (C)           20.278024
Ice cream  eaten     0.470000
dtype: float64

In [55]:
# Exercises: Create a pandas dataframe with three variables:
# 1) integers from 0 to 10
# 2) their square
# 3) their log

In [80]:
nums = np.array(range(11))
nums

sqr = np.square(nums)
sqr

logs = np.log(nums)
logs

labels = [ 'Integer', 'Square root', 'logs']

D = { labels[0]: nums, labels[1]: sqr, labels[2]: logs}

df = pd.DataFrame(data=D)
df

/tmp/ipykernel_1718/4126631105.py:7: RuntimeWarning: divide by zero encountered in log
  logs = np.log(nums)

    Integer  Square root      logs
0         0            0      -inf
1         1            1  0.000000
2         2            4  0.693147
3         3            9  1.098612
4         4           16  1.386294
5         5           25  1.609438
6         6           36  1.791759
7         7           49  1.945910
8         8           64  2.079442
9         9           81  2.197225
10       10          100  2.302585